Creando registro de toma de presión
Luz-Gomez/MisionTIC2022-C3-G-E-4-48-Proyecto-Health-Control pull request #23
Opened 2021-09-10 04:40 UTC by Luz-Gomez

Creada la pagina HTML para registrar los datos de toma de presión, favor su revisión, autorizar y hacer la mezcla. Muchas gracias

2021-09-10 19:18 UTC, Natyctoc requested changes
Luz, debes cambiar el el lenguaje a español, en la etiqueta lang="en" lo pones lang="es"
Tienes errores de ortografía en el segundo h2 la palabra presión debe llevar tilde.
El texto informativo no debería ir en un formulario ya que los formularios son usados para que el usuario ingrese datos no para mostrarlos, sugiero que lo cambies por un paragraph o un heading.
Sugiero que los inputs son los que deben ir dentro de un formulario, por la razón arriba mencionada. No creo que sea bueno dejarlos como lista.

Queda pendiente enlazar la tabla de los registros con el botón de submit cuando realices el javascript, pero esto es sólo como mención. Te quedó muy bien, me encantó que tomaras los mismos colores que sugerí en el index. Gran trabajo!

2021-09-10 22:05 UTC, Luz-Gomez commented
Buenas tardes, se realizaron las correcciones solicitadas y se ajusto aceptando las sugerencias. La tabla se mantiene, es para mostrar datos que mostrara una vez se codifique la acción en el botón Guardar. Muchas gracias

2021-09-11 15:44 UTC, Natyctoc commented
Si mita yo sólo te recordé que hay que enlazarla ya eso es cuando trabajes el javascript.

2021-09-11 15:50 UTC, Natyctoc approved these changes
Listo mi lucesita, queda pendiente arreglar la ortografía en los label de presión diastólica  y sistólica, les falta la tilde en presión pero eso ya es un cambio menor así que los voy a aprobar y luego tu le haces ese pequeño ajuste.

2021-09-11 15:51 UTC, Natyctoc commented
Quedó pendiente un ajuste ortográfico en los labels.

2021-09-11 15:51 UTC, merged