Migrando mis paginas
Luz-Gomez/MisionTIC2022-C3-G-E-4-48-Proyecto-Health-Control pull request #54
Opened 2021-09-21 18:03 UTC by Luz-Gomez

Creacion inicial de mis paginas en Vue, afecte el index.js, App.vue y otros archivos de configuracion. Nataly agradeceria tu acostumbrada ayuda con la revision y merge

2021-09-21 19:09 UTC, Natyctoc requested changes
Hola luz, mira en datosusuario.vue tomapresion.vue y otro.vue falta un espacio al final de documento, porfa corrige eso para poderlo mezclar

2021-09-21 19:37 UTC, Luz-Gomez commented
Gracias Nataly, ya envie los ajustes.

2021-09-21 21:37 UTC, Luz-Gomez commented
Listos los ajuste, gracias Nataly

2021-09-22 00:52 UTC, Natyctoc approved these changes

2021-09-22 00:52 UTC, merged